_BASE_: [
  '../datasets/ematerials.yml',
  '../runtime.yml',
  './_base_/ppyolo_tiny.yml',
  './_base_/optimizer_365e.yml',
  './_base_/ppyolo_tiny_reader.yml',
]

#snapshot_epoch: 8
weights: output/clip/ppyolo_tiny_365e_ematerials/model_final
