_BASE_: [
  '../datasets/ematerials.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/optimizer_365e.yml',
  './_base_/ppyolov2_reader.yml',
]

#snapshot_epoch: 8
weights: output/ppyolov2_r50vd_365e_ematerials/model_final
