_BASE_: [
  '../datasets/layoutv2.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/optimizer_365e.yml',
  './_base_/ppyolov2_reader_layout.yml',
]

snapshot_epoch: 10
weights: output/ppyolov2_r50vd_dcn_365e_layoutv2/model_final

