_BASE_: [
  '../datasets/format.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/optimizer_650e.yml',
  './_base_/ppyolov2_reader_format.yml',
]

snapshot_epoch: 10
weights: output/ppyolov2_r50vd_dcn_650e_layout/model_final
