metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: ematerials_clip/paddletype/
    data_fields: ['image', 'gt_bbox', 'gt_class']

TestDataset:
  !ImageFolder
    image_dir: test
    anno_path: annotations/instance_test.json
    dataset_dir: ematerials_clip/paddletype/
EvalDataset:
  !COCODataSet
    image_dir: test
    anno_path: annotations/instance_test.json
    dataset_dir: ematerials_clip/paddletype/
